"""Report rendering: Markdown (always) + one-page PDF (optional).

The PDF is generated by reportlab when installed. If reportlab is missing,
the function logs and returns None — local devs without the dep don't see a
hard failure. The PDF layout deliberately mirrors the structure a partner
expects on a one-pager: name, scoring radar (text-rendered for portability),
regulatory / sovereignty tags, vintage match, sources, rationale.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from .schema import ScoredCompany, VCScoutOutput


logger = logging.getLogger(__name__)


def save_markdown_report(
    urls: list[str],
    output: VCScoutOutput,
    outputs_dir: Path | None = None,
) -> str:
    """Render the full run to a timestamped Markdown file. Returns the path."""
    outputs_dir = outputs_dir or (Path(__file__).resolve().parent.parent / "outputs")
    outputs_dir.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    path = outputs_dir / f"vc_scout_report_{ts}.md"

    sources_block = "\n".join(f"- {u}" for u in urls)
    themes_block = ", ".join(output.themes) if output.themes else "—"
    companies_block = _render_companies_md(output.companies)

    path.write_text(
        f"""# VC Scout Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Sources Analyzed
{sources_block}

## Headline Summary
{output.headline_summary}

## Visible Only When Combined
{output.visible_only_when_combined}

## Why It Matters
{output.why_it_matters}

## Possible Investment Angle
{output.possible_investment_angle}

## Contrarian View
{output.contrarian_view}

## Risks or Limitations
{output.risks_or_limitations}

## Themes
{themes_block}

## Scored Companies / Startups
{companies_block}
""",
        encoding="utf-8",
    )
    return str(path)


def _render_companies_md(companies: list[ScoredCompany]) -> str:
    if not companies:
        return "_(no companies surfaced in this run)_"
    sorted_companies = sorted(companies, key=lambda c: c.score_total, reverse=True)
    lines: list[str] = []
    for c in sorted_companies:
        sources_str = ", ".join(c.sources) if c.sources else "—"
        lines.append(
            f"### {c.name}  —  **{c.score_total}/10**\n"
            f"- **Scores:** market {c.score_market} · team {c.score_team} · "
            f"product {c.score_product} · defensibility {c.score_defensibility} · "
            f"interest {c.score_interest}\n"
            f"- **Regulatory:** {c.regulatory_tag}\n"
            f"- **Sovereignty thesis:** {c.sovereignty_tag}\n"
            f"- **Vintage match:** {c.vintage_match}\n"
            f"- **Funding signal:** {c.funding_signal}\n"
            f"- **Sources:** {sources_str}\n"
            f"- **Rationale:** {c.rationale}\n"
        )
    return "\n".join(lines)


def generate_onepagers(
    companies: list[ScoredCompany],
    outputs_dir: Path | None = None,
    min_score: float = 7.5,
) -> list[str]:
    """Generate a one-page PDF for every company at or above `min_score`.

    Returns the list of generated PDF paths. If reportlab is unavailable the
    function is a logged no-op — callers don't need to handle the import.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        )
    except ImportError:
        logger.info("reportlab not installed — skipping PDF one-pager generation")
        return []

    outputs_dir = outputs_dir or (Path(__file__).resolve().parent.parent / "outputs" / "onepagers")
    outputs_dir.mkdir(parents=True, exist_ok=True)

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], spaceAfter=4, fontSize=18)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], spaceAfter=2, fontSize=11, textColor=colors.grey)
    body = ParagraphStyle("Body", parent=styles["BodyText"], fontSize=10, leading=14)

    paths: list[str] = []
    ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    for c in companies:
        if c.score_total < min_score:
            continue
        safe_name = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in c.name)[:60]
        pdf_path = outputs_dir / f"{safe_name}_{ts}.pdf"

        doc = SimpleDocTemplate(
            str(pdf_path), pagesize=A4,
            leftMargin=2 * cm, rightMargin=2 * cm,
            topMargin=2 * cm, bottomMargin=2 * cm,
        )
        story = [
            Paragraph(c.name, h1),
            Paragraph(f"VC Scout one-pager · generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", h2),
            Spacer(1, 0.3 * cm),
            _score_table(c),
            Spacer(1, 0.4 * cm),
            Paragraph("<b>Regulatory exposure</b>", h2),
            Paragraph(c.regulatory_tag or "—", body),
            Paragraph("<b>EU sovereignty thesis</b>", h2),
            Paragraph(c.sovereignty_tag or "—", body),
            Paragraph("<b>Vintage match</b>", h2),
            Paragraph(c.vintage_match or "—", body),
            Paragraph("<b>Funding signal</b>", h2),
            Paragraph(c.funding_signal or "—", body),
            Paragraph("<b>Rationale (with source citations)</b>", h2),
            Paragraph(c.rationale or "—", body),
            Paragraph("<b>Sources</b>", h2),
            Paragraph("<br/>".join(c.sources) if c.sources else "—", body),
        ]
        doc.build(story)
        paths.append(str(pdf_path))
    return paths


def _score_table(c: ScoredCompany):
    """Inline-import-friendly score table for the PDF."""
    from reportlab.lib import colors
    from reportlab.lib.units import cm
    from reportlab.platypus import Table, TableStyle

    data = [
        ["Market", "Team", "Product", "Defensibility", "Interest", "Total"],
        [
            c.score_market, c.score_team, c.score_product,
            c.score_defensibility, c.score_interest, f"{c.score_total}",
        ],
    ]
    tbl = Table(data, colWidths=[2.6 * cm] * 5 + [2.4 * cm])
    tbl.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BACKGROUND", (-1, 1), (-1, 1), colors.HexColor("#f1d70f")),
            ("FONTNAME", (-1, 1), (-1, 1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
            ("TOPPADDING", (0, 0), (-1, 0), 6),
        ])
    )
    return tbl
